name: 'Build with CMake'
description: 'Build project'
inputs:
  shell:
    description: 'The shell to execute steps'
    required: false
    default: 'bash'

runs:
  using: composite
  steps:
    - name: Configure Release
      shell: ${{ inputs.shell }}
      run: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release

    - name: Build
      shell: ${{ inputs.shell }}
      run: cmake --build build --parallel 4

    - name: Create install (for those that may want a lib pre-installed)
      shell: ${{ inputs.shell }}
      run: cmake --install build --parallel 4 --prefix install

    - name: Check if it links to the install
      shell: ${{ inputs.shell }}
      run: |
          cmake -S example -B example-build -G Ninja -DCMAKE_PREFIX_PATH=../install -DCMAKE_BUILD_TYPE=Release
          cmake --build example-build --parallel 4

    - name: Test Ubuntu
      shell: ${{ inputs.shell }}
      if: matrix.os == 'ubuntu-latest'
      run: ctest --test-dir build --output-on-failure --verbose

    - name: Test Others
      shell: ${{ inputs.shell }}
      if: matrix.os != 'ubuntu-latest'
      run: ctest --test-dir build --output-on-failure --verbose -E 'udp_.*_test' # Windows does not work with UDP Broadcast to INADDR_ANY in CI/CD