name: Deploy library

on:
  push:
    tags:
      - 'v*'

jobs:
  make-libs:
    name: Building and deploying on ${{ matrix.os }} - ${{ matrix.compiler }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            compiler: gcc
            terminal: bash
            archive_ext: tar.gz

          - os: windows-latest
            compiler: msvc
            terminal: bash
            archive_ext: zip

          - os: windows-latest
            compiler: mingw
            terminal: msys2 {0}
            archive_ext: zip

    defaults:
      run:
        shell: ${{ matrix.terminal }}

    steps:
      - uses: actions/checkout@v7

      - name: Setup
        uses: $/.github/actions/setup_compiler
        with:
          compiler: ${{ matrix.compiler }}
          shell: ${{ matrix.terminal }}

      - name: Build & Test
        uses: $/.github/actions/build_and_test
        with:
          shell: ${{ matrix.terminal }}

      - name: Archive
        run: |
            if [ "${{ matrix.archive_ext }}" = "tar.gz" ]; then
                tar -czf lunaris-socket-${{ matrix.os }}-${{ matrix.compiler }}.tar.gz install
            else
                powershell Compress-Archive -Path install\* -DestinationPath lunaris-socket-${{ matrix.os }}-${{ matrix.compiler }}.zip
            fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: lunaris-${{ matrix.os }}-${{ matrix.compiler }}
          path: |
            *.tar.gz
            *.zip
            
  release:
    needs: make-libs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
        with:
            path: dist
            merge-multiple: true

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
