name: CMake CTest pipeline
on:
  workflow_dispatch:


jobs:
  test-project:
    name: Check project
    runs-on: ubuntu-24.04
    steps:
      - name: Build
        uses: LunarisLib/actions/CMake@master
        with:
            build_configuration: 'Release'
            checkout: true
            artifact_name: 'LunarisSocket'
            
      - name: Test Project
        uses: threeal/ctest-action@v1.1.0